title: Department 21
author:
  name: Noam Sain
  email: greg@department21.org

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: Gnome Sayings, by Noam Saenz

# Build settings

theme: minima

url: "https://www.department21.org" # the base hostname & protocol for your site

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  skin: auto

  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: github,         user_url: "https://github.com/greg-raven" }
  #   - { platform: keybase,        user_url: "https://keybase.io/gregraven" }
  #   - { platform: twitter,        user_url: "https://twitter.com/gregraven" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/@GregRaven" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
  - links.md
  - search.html

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: true

paginate: 20
