title: Department 21
author:
  name: Noam Sain
  email: greg@department21.org

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

description: Gnome Sayings, by Noam Saenz

# Build settings

theme: minima

# the base hostname & protocol for your site

url: "https://www.department21.org"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Theme-specific settings

minima:
  skin: auto

# If you want to link only specific pages in your header, uncomment this
# and add the path to the pages in order as they should show up.

header_pages:
  - about.md
  - links.md
  - search.html

# Set to `true` to show excerpts on the homepage.

show_excerpts: true

paginate: 20
